# Site wide configuration
title:            Rakibul's Blog
email:            rytotul@yahoo.com
description:      Trash Bin of my Lazy Brain
url:              https://rakibul-yeasin-blog.github.io
keywords:         ["blog", "rakibul", "yeasin"]
categories:       ["automation", "scripts"]

# Jekyll configuration
timezone:          Asia/Dhaka
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Site Owner configuration
owner:
  name:               Rakibul Yeasin
  avatar:             Icon.png
  job:                "CS Student, Developer"
  bio:                "Trash Bin of ny Lazy Brain."
  email:
  disqus-shortname: rakibuls-blog
  twitter: rytotul
  facebook: dreygur
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: dreygur
  gitlab: dreygur
  stackoverflow: 7277428/totul
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: dreygur
